### ISSUE TITLE
Consider rename?

### ISSUE THREAD

**Issue by craigh** [zikula/DynamicFormPropertyBundle#14]
Wondering if this bundle needs a more "marketable" name?

1. DynaFormBundle
2. DynamoBundle ✅ 👎
3. DynamicFormBundle ✅
4. DynaPropBundle
5. FormMakerBundle ❌
6. FormDynamoBundle ✅ 👎
7. DynamicFormFieldBundle ✅
8. FormBuilderBundle ✅ ✅

**Comment by craigh** [comment]
**Dynamo**
a machine for converting mechanical energy into electrical energy; a generator.

**Comment by OGProgrammer** [comment]
I feel like devs may be thinking this is related to DynamoDB (AWS service) - Perhaps something more generic like "Advanced" or just "Dynamic" Form Types is the way to go. I think this is a good time to reach out to Ryan Weaver, want me to start an email thread?

**Comment by craigh** [comment]
Maybe **FormDynamoBundle** is more clear then.

I had done some initial searching on "Dynamo" and noticed DynamoDB but didn't think that would be an issue.

**Comment by weaverryan** [comment]
Dynamo sounds cool, but I personally didn't know what that word meant. The clearest to me are `DynamicFormFieldBundle` (very similar to the current name, but I "think" that "field" better conveys what it does than property), or maybe `FormBuilderBundle` (there is a similar bundle, but not sure that the audiences would overlap https://github.com/Novactive/NovaFormBuilderBundle) `

**Comment by craigh** [comment]
I had previously seen NovaFormBuilderBundle as well, but (like most similar projects) it is tied quite tightly to a CMS of some kind. Indeed, this project grew from the Zikula CMS. but I have intentionally eliminated any dependencies.

**Comment by Guite** [comment]
My vote still goes to `DynamicFormBundle` as it is both precise and clear.
`FormBuilderBundle` is also very nice because it is even more expressive.

**Comment by craigh** [comment]
Changed to **DynamicFormBundle**
