### ISSUE TITLE
Bundle is locked to twig-bundle 5.4 rather then ^5.4 

### ISSUE THREAD

**Issue by On5-Repos** [zikula/DynamicFormPropertyBundle#20]
Compose is locked on 5.4 rather locking to any 5.4.* 

**"symfony/twig-bundle": "5.4 || ^6.0"**

**Comment by Guite** [comment]
Thanks @On5-Repos for reporting this issue.

It should be fixed with 2b2f950.

Can you please verify whether it works fine for you and close the ticket afterwards?

**Comment by On5-Repos** [comment]
its working, thanks.
