### ISSUE TITLE
symfony 6 compatibility issue

### ISSUE THREAD

**Issue by On5-Repos** [zikula/DynamicFormPropertyBundle#21]
Package is locked to **[symfony/contracts]: ^2**

but above package been remove in 6 and replaced with **symfony/deprecation-contracts**

Can this be fixed? currently we are unable to upgrade from 5.4 to 6

**Comment by craigh** [comment]
Hi @On5-Repos I'm willing to change it but would like to maintain compatibility with 5.4. Any idea how to do that?

**Comment by On5-Repos** [comment]
> [symfony/contracts]: ^2

I am running some tests to keep compatibility and I will report back soon.

**Comment by craigh** [comment]
I think we just need to replace
```json
        "symfony/contracts": "^2",
```
with

```json
        "symfony/event-dispatcher-contracts": "^2.0 || ^3.0",
        "symfony/translation-contracts": "^2.0 || ^3.0",
```

**Comment by On5-Repos** [comment]
yes correct it seems to work

**Comment by craigh** [comment]
changed [here](https://github.com/zikula/DynamicFormBundle/commit/5fa2b8f84f18dff5f0e09e308c61634be74baa57)

**Comment by craigh** [comment]
but now a bunch of stuff is broken in tests and things... I hope it still works for you. I don't have time to fix it up in the near future. I would welcome a PR to correct.

**Comment by On5-Repos** [comment]
leave the issue open I will work on it and report back.

**Comment by On5-Repos** [comment]
#22
